import "./globals.css";
import QueryProviders from "@/lib/providers/query-providers";
import AuthProviders from "@/lib/providers/auth-providers";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { dmSans, barlow, inter } from "@/fonts";

export const metadata = {
  title: "Tanpa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${dmSans.variable} ${barlow.variable} flex flex-col min-h-screen`}
      >
        <QueryProviders>
          <AuthProviders>
            <Navbar />
            {children}
            <Footer />
          </AuthProviders>
        </QueryProviders>
      </body>
    </html>
  );
}
